### ISSUE TITLE
My Kwagsh wallet gui or cli will not synk past block 41178 and none of the sites are working 

### ISSUE THREAD

**Issue by rpbigpapa** [laugh26/kwagsh-gui#1]
Hi last week i started my wallet and i had over 26000000 Kwagsh i sent half to altex and they went through fine then yesterday i seen someone was buying for 1 sat each which ment over $1000 i could have gotten ut now the wallet will not synk even after rebuilding it with 12 word key or other keys it starts fine then gets to block 41178 and i start getting unknown top block: 41178 -> 66142 [24964 blocks (34 days) behind]
2018-Jul-11 14:00:22.801848 INFO [protocol] SYNCHRONIZATION started
2018-Jul-11 14:00:23.006846 INFO [Blockchain] Block f16aa6ba0adfcf095e29a18647a166c816d4975563030f1fbaf022dcf6d02b87, has too weak proof of work: bb775dfc0a7fb8becf87e229170cefd70575865a142948b466b52b5909000000, expected difficulty: 2184750367210
over and over both in the cli wallet and in gui
but also the block explorer and pool https://kgh.kwagsh.xyz is gone gives kgh.kwagsh.xyz’s server IP address could not be found. and the other pool is there but has no mining address or any miners so did the Dev just abandon us i believe because no miners mining and the black explorer server saying offline means i have just been screwed out of over $1000 because after trying to end my coins all night the buyer is now gone and would have bought all my kwagsh please tell me this can and will be fixed cause i spent over a week mining over 26000000 kwagsh should have known the ne time i got in as one of the first 5 miners and score a grip only to have this happen very depressing esp after being diag, with congestive hart failure a month ago after having a hart attack and this is not helping

**Comment by rpbigpapa** [comment]
so i guess im screwed ot over $1000 because still wallet will not synk and they say its safer to keep them in a off line wallet so you control your keys in case anything happens other that the Dev taking their servers off line so now no one can mine at all and im stuck with coins i cant move just as they become worth something can anyone help me hell ill pay or a amazon server long enough to get my coins moved whats up guys this sucks

**Comment by laugh26** [comment]
@rpbigpapa go get their new wallet in kwagsh repo. This is the old code
